# This is a basic workflow to help you get started with Actions

name: Client/Server test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  server:
    outputs:
      server_ip: ${{ steps.server_ip.outputs.test }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - id: server_ip
        run: |
          IP=($(curl -s http://ipinfo.io/json | jq '.ip' | sed -e 's/^"//' -e 's/"$//'))
          echo "::set-output name=test::$IP"
          
      - name: Start Server
        run: |
          wget https://github.com/gdams/client-server-actions-test/releases/download/petclinic/spring-petclinic-2.3.1.BUILD-SNAPSHOT.jar
          java -jar spring-petclinic-2.3.1.BUILD-SNAPSHOT.jar > /dev/null 2>&1 &

  client:
    needs: server
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.server.outputs.server_ip}}
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Apache JMeter
        run: wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.5.zip -O apache-jmeter.zip
        
      - name: Extract Apache JMeter
        run: unzip apache-jmeter.zip
        
      - name: Startup Apache JMeter
        run: ./apache-jmeter-5.5/bin/jmeter -n -t petclinic.jmx -l output.jtl -JHOST=${{ needs.server.outputs.server_ip}}
        
      - uses: actions/upload-artifact@v2
        with:
          name: jmeter-output
          path: output.jtl

      
